version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: matplotlib
    versions:
    - 3.3.0
